#!/bin/csh -f

if ($#argv != 2) then
	echo "usage: contest team1name team2name"
	exit 1
endif

echo "contest: Removing old stuff"
rm -f *.a
rm -f soccer
rm -f core

if ($1 != $2) then
	echo "contest: Moving to ./teams/"{$1}" ."
	echo "contest: Compiling libraries for the " {$1} " team."
	cd teams/{$1}
	make libwest.a
	cp libwest.a ../..
	make libcommon.a
	cp libcommon.a ../../libwestcommon.a
	echo "contest: Moving to ./teams/"{$2}" ."
	echo "contest: Compiling libraries for the " {$2} " team."
	cd ../{$2}
	make libeast.a
	cp libeast.a ../..
	make libcommon.a
	cp libcommon.a ../../libeastcommon.a
	cd ../..
	echo "contest: Compiling and linking soccer."
	make soccer
else
	cd teams/{$1}
	echo "contest: This team will play against itself."
	echo "contest: WARNING some teams will fail to link in this case."
	echo "contest: Moving to ./teams/"{$2}" ."
	echo "contest: Compiling libraries for the " {$1} " team."
	make libeast.a
	make libwest.a
	make libcommon.a
	cp libeast.a ../../libeast.a
	cp libwest.a ../../libwest.a
	cp libcommon.a ../../libcommon.a
	cd ../..
	echo "contest: Compiling and linking soccer."
	make soccerboth
endif
echo "contest: starting a game."
./soccer -p 7
